### ISSUE TITLE
Create better testing

### ISSUE THREAD

**Issue by Hammie217** [Hammie217/PyCtrl#1]
Create a better testing regime in text.py

**Comment by niangomes** [comment]
i need a better descrption to help u

**Comment by Hammie217** [comment]
> i need a better descrption to help u

Hi Niangomes, glad to hear you're interested in helping. I'm fairly new to unit-testing and was hoping you could offer some insight into what would be useful. Personally I was thinking of creating a test that can automatically test the functionality of single or multichoice functions directly. I'm not sure how this can be done so feel free to be creative. 

Thanks,

**Comment by ebarnsli** [comment]
I got you

**Comment by Hammie217** [comment]
solved in #4
